const fs = require("fs");
const path = require("path");
const MarkdownIt = require("markdown-it");
const markdownItAnchor = require("markdown-it-anchor");

const contentDir = path.join(__dirname, "..", "content");
const buildDir = path.join(__dirname, "..", "build");
const outputFile = path.join(buildDir, "data.js");
const assetsDir = path.join(__dirname, "..", "assets");
const outputHtml = path.join(buildDir, "index.html");

const md = new MarkdownIt({
  html: false,
  linkify: true,
});
md.use(markdownItAnchor, {
  slugify: (value) =>
    value
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-zA-Z0-9\\s-]/g, "")
      .trim()
      .replace(/\\s+/g, "-")
      .toLowerCase(),
});

function splitFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    return { frontmatter: null, body: text.trim() };
  }

  return { frontmatter: match[1], body: match[2].trim() };
}

function parseFrontmatter(frontmatter) {
  if (!frontmatter) {
    return {};
  }

  const data = {};
  frontmatter.split("\n").forEach((line) => {
    const parts = line.split(":");
    if (parts.length < 2) {
      return;
    }
    const key = parts[0].trim();
    const value = parts.slice(1).join(":").trim();
    if (key) {
      data[key] = value;
    }
  });

  return data;
}

function stripMarkdown(value) {
  return value.replace(/\*\*/g, "").replace(/\*/g, "").trim();
}

function extractLabeledTitles(body) {
  let en = "";
  let hu = "";

  body.split("\n").forEach((line) => {
    let cleaned = line.trim();
    if (!cleaned) {
      return;
    }
    cleaned = cleaned.replace(/^>\s*/, "");
    cleaned = stripMarkdown(cleaned);

    const huMatch = cleaned.match(/^Magyar:\s*(.+)$/i);
    if (huMatch && !hu) {
      hu = huMatch[1].trim();
    }

    const enMatch = cleaned.match(/^Angol:\s*(.+)$/i);
    if (enMatch && !en) {
      en = enMatch[1].trim();
    }
  });

  return { en, hu };
}

function stripLabeledTitleLines(body) {
  const lines = body.split("\n");
  const filtered = lines.filter((line) => {
    const trimmed = line.trim();
    if (!trimmed) {
      return true;
    }
    const cleaned = stripMarkdown(trimmed.replace(/^>\s*/, ""));
    return !/^Angol:\s*/i.test(cleaned) && !/^Magyar:\s*/i.test(cleaned);
  });
  return filtered.join("\n").trim();
}

function extractHeadingTitles(body) {
  const headingMatch = body.match(/^#\s+(.*)$/m);
  if (!headingMatch) {
    return { en: "", hu: "" };
  }

  let heading = headingMatch[1].trim();
  heading = heading.replace(/^[^A-Za-z0-9]*\d+\s*[–—-]\s*/, "").trim();
  const headingCore = heading.split(/\s[–—]\s/)[0].trim();
  if (!headingCore) {
    return { en: "", hu: "" };
  }

  const parenMatch = headingCore.match(/^(.*?)\s*\((.+)\)\s*$/);
  if (parenMatch) {
    return { en: parenMatch[1].trim(), hu: parenMatch[2].trim() };
  }

  return { en: headingCore, hu: "" };
}

function parseMarkdown(text) {
  const { frontmatter, body } = splitFrontmatter(text);
  const meta = parseFrontmatter(frontmatter);
  const labeled = extractLabeledTitles(body);
  const heading = extractHeadingTitles(body);

  const en = labeled.en || heading.en || meta.en || "";
  const hu = labeled.hu || heading.hu || meta.hu || "";
  const bodyWithoutLabels = stripLabeledTitleLines(body);
  const descHtml = md.render(bodyWithoutLabels).trim();

  return { en, hu, descHtml };
}

const files = fs
  .readdirSync(contentDir)
  .filter((file) => file.endsWith(".md"))
  .sort();

const items = files.map((file) => {
  const fullPath = path.join(contentDir, file);
  const text = fs.readFileSync(fullPath, "utf8");
  return parseMarkdown(text, file);
});

const output = `// Generated by scripts/build-data.js\nconst items = ${JSON.stringify(
  items,
  null,
  2
)};\n`;

fs.mkdirSync(buildDir, { recursive: true });
fs.writeFileSync(outputFile, output, "utf8");
const htmlSource = path.join(assetsDir, "index.html");
if (!fs.existsSync(htmlSource)) {
  throw new Error("Missing assets/index.html");
}
fs.copyFileSync(htmlSource, outputHtml);

console.log(`Wrote ${items.length} items to ${outputFile}`);
console.log(`Copied ${htmlSource} to ${outputHtml}`);
